services:
  osmium:
    platform: linux/amd64 #obligatoire pour les users macos vu que mysql existe pas nativement sous ARM
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app